"""
Django settings for healthy_sabji project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR,)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j4q#yl6$z@4zyuxa_9ii+$y+%yeui8od8uh__!9%*2tj-f-r*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'sabji',
    'accounts',
    'orders',
    'cart',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'healthy_sabji.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sabji.processors.productprocessor',
                'sabji.processors.categoryprocessor',
                'sabji.processors.discountprocessor',
                'sabji.processors.cartprocessor',
                'sabji.processors.bestsellerprocessor',
            ],
        },
    },
]

WSGI_APPLICATION = 'healthy_sabji.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'HealthySabji',   
        'USER': 'postgres',       
        'PASSWORD': '1234',  
        'HOST': 'localhost',   
        'PORT': '5432',   
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'


LOGIN_URL = '/login/'



SESSION_COOKIE_AGE = 3600 # 1 hour


SESSION_EXPIRE_AT_BROWSER_CLOSE = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dhamisubash866@gmail.com'
EMAIL_HOST_PASSWORD = 'siuc eumd dour nwpl'



JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "Healthy Sabji",

    # Title on the login screen
    "site_header": "Healthy Sabji",

    # Title on the brand
    "site_brand": "Healthy Sabji",

    # Logo to use for your site (adjust path according to your static files)
    "site_logo": "../static/img/Healthy.png",  # Assuming you place a logo here

    # Logo for login page (if same as site_logo, you can leave as None)
    "login_logo": None,

    # Logo for dark theme login (optional)
    "login_logo_dark": None,

    # CSS classes applied to the logo
    "site_logo_classes": "img-circle",

    # Favicon
    "site_icon": "../static/img/Healthy.png",  # Optional if you have a favicon

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Healthy Sabji",

    # Copyright
    "copyright": "Healthy Sabji Pvt. Ltd.",

    # Search models
    "search_model": ["auth.User", "auth.Group", "products.Product"],

    # User avatar field (optional)
    "user_avatar": None,

    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "products"},
    ],

    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"name": "Help & Support", "url": "https://healthysabji.com/support", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth", 
        "products", 
        "orders", 
        "delivery", 
        "users"
    ],

    "custom_links": {
        "products": [{
            "name": "Add Bulk Products",
            "url": "bulk_add_products", 
            "icon": "fas fa-plus-square",
            "permissions": ["products.add_product"]
        }]
    },

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "products": "fas fa-carrot",         # For your vegetable/fruits products
        "orders": "fas fa-shopping-cart",     # For orders
        "delivery": "fas fa-truck",            # For delivery team
        "users": "fas fa-user-friends",        # For normal users/customers
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    "related_modal_active": True,

    #############
    # UI Tweaks #
    #############
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "products.product": "single",
    },

    "language_chooser": True,
}
